#

homeassistant:
  packages:
    minpakke !include_dir_named packages/minpakke
    minpakke2 !include_dir_named packages/minpakke2

# Or if used at file level

homeassistant:
  packages:
    minpakke: !include packages/minpakke/minpakkefil.yaml
    minpakke_fil2: !include packages/minpakke/minpakkefil2.yaml
    minpakke2: !include packages/minpakke2/minpakkefil.yaml
